### ISSUE TITLE
Can't install with pip : No matching distribution found for dynofunc

### ISSUE THREAD

**Issue by filol** [sodiray/dynofunc#23]
Hi, i just try to install your lib but I have some errors. It seem's that it complain about my python version that doesn't meet the requirement of python >= 3 but I'm using python 3.9, any idea ?

Also you have a warning with the readme

```
user@MacBook-Pro:~/Documents/⚡ ⇒  pip3 -vvv install dynofunc                
Using pip 21.0.1 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-ephem-wheel-cache-be37nipu
Created temporary directory: /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-req-tracker-r44tjnxh
Initialized build tracking at /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-req-tracker-r44tjnxh
Created build tracker: /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-req-tracker-r44tjnxh
Entered build tracker: /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-req-tracker-r44tjnxh
Created temporary directory: /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-install-c_p390fk
1 location(s) to search for versions of dynofunc:
* https://pypi.org/simple/dynofunc/
Fetching project page and analyzing links: https://pypi.org/simple/dynofunc/
Getting page https://pypi.org/simple/dynofunc/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/dynofunc/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/dynofunc/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/58/28/ac1637a50967d3067780cfdcf922e32e2faf24267df0b638358720df5d1e/dynofunc-1.0.0.tar.gz#sha256=35e37ef8e37bebcd7ee07a4b88c2b7cf9e5fb7f3eb9d96db30aa725b5fff4de6 (from https://pypi.org/simple/dynofunc/) (requires-python:>=3), version: 1.0.0
Given no hashes to check 1 links for project 'dynofunc': discarding no candidates
Collecting dynofunc
  Created temporary directory: /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-unpack-j7pq2hoc
  Looking up "https://files.pythonhosted.org/packages/58/28/ac1637a50967d3067780cfdcf922e32e2faf24267df0b638358720df5d1e/dynofunc-1.0.0.tar.gz" in the cache
  Current age based on date: 8621
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 8621
  Using cached dynofunc-1.0.0.tar.gz (14 kB)
  Added dynofunc from https://files.pythonhosted.org/packages/58/28/ac1637a50967d3067780cfdcf922e32e2faf24267df0b638358720df5d1e/dynofunc-1.0.0.tar.gz#sha256=35e37ef8e37bebcd7ee07a4b88c2b7cf9e5fb7f3eb9d96db30aa725b5fff4de6 to build tracker '/private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-req-tracker-r44tjnxh'
    Running setup.py (path:/private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-install-c_p390fk/dynofunc_c3eaa9e701f442e08560cbb39efec22a/setup.py) egg_info for package dynofunc
    Created temporary directory: /private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-pip-egg-info-ax3k1sko
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-install-c_p390fk/dynofunc_c3eaa9e701f442e08560cbb39efec22a/setup.py", line 5, in <module>
        with open('README.md', 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
WARNING: Discarding https://files.pythonhosted.org/packages/58/28/ac1637a50967d3067780cfdcf922e32e2faf24267df0b638358720df5d1e/dynofunc-1.0.0.tar.gz#sha256=35e37ef8e37bebcd7ee07a4b88c2b7cf9e5fb7f3eb9d96db30aa725b5fff4de6 (from https://pypi.org/simple/dynofunc/) (requires-python:>=3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement dynofunc
ERROR: No matching distribution found for dynofunc
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'dynofunc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('dynofunc')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 320, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('dynofunc'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for dynofunc
Removed dynofunc from https://files.pythonhosted.org/packages/58/28/ac1637a50967d3067780cfdcf922e32e2faf24267df0b638358720df5d1e/dynofunc-1.0.0.tar.gz#sha256=35e37ef8e37bebcd7ee07a4b88c2b7cf9e5fb7f3eb9d96db30aa725b5fff4de6 from build tracker '/private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-req-tracker-r44tjnxh'
Removed build tracker: '/private/var/folders/93/5gnyqj597qqg9dnrb1nx2jym0000gn/T/pip-req-tracker-r44tjnxh'
user@MacBook-Pro:~/Documents/⚡ ⇒   
```

**Comment by thedonut** [comment]
It looks like the last build a while ago failed at the last step, publishing...

**Comment by redigaffi** [comment]
I was able to install it with poetry directly from this git repo:

`
poetry add git+https://github.com/rayepps/dynofunc@develop
`
